#!/usr/bin/env python3
"""Turn the game records dumped by dump_games.py into port/m2/gamedb.inc.
usage: gen_gamedb.py EMULATOR.EXE dumpprefix out.inc"""
import struct, sys

exe_path, prefix, out = sys.argv[1:4]
exe = open(exe_path, "rb").read()
mem = open(prefix + ".mem", "rb").read()
heap = open(prefix + ".heap", "rb").read()
MB, HB = 0x528000, 0x20000000


def rd(va, n=4):
    if MB <= va < MB + len(mem):
        return mem[va - MB:va - MB + n]
    if HB <= va < HB + len(heap):
        return heap[va - HB:va - HB + n]
    if 0x508000 <= va < 0x528000:
        o = 0x106600 + va - 0x508000
        return exe[o:o + n]
    if 0x401000 <= va < 0x508000:
        o = 0x400 + va - 0x401000
        return exe[o:o + n]
    return None


def u32(va):
    b = rd(va)
    return struct.unpack("<I", b)[0] if b else 0


def cstr(va):
    b = rd(va, 64) if va else None
    if not b:
        return None
    s = b.split(b"\0")[0]
    return s.decode("latin1") if s and all(32 <= c < 127 for c in s) else None


def decode_hook(fn):
    """Per-game hook functions are tiny stubs: optionally set the hook
    callback, then mov eax,addr ; jmp i960 hook/stop installer."""
    if not fn:
        return ("M2_HOOK_NONE", 0)
    code = rd(fn, 32)
    i = 0
    kind = None
    if code[:2] == b"\xc7\x81":           # mov [ecx+disp32], imm32 (hook callback)
        i = 10
    if code[i:i + 3] != b"\x83\xc1\x40":  # add ecx,0x40
        return ("M2_HOOK_UNKNOWN", fn)
    i += 3
    if code[i] != 0xb8:
        return ("M2_HOOK_UNKNOWN", fn)
    addr = struct.unpack_from("<I", code, i + 1)[0]
    i += 5
    if code[i] != 0xe9:
        return ("M2_HOOK_UNKNOWN", fn)
    tgt = fn + i + 5 + struct.unpack_from("<i", code, i + 1)[0]
    kind = {0x4c25f0: "M2_HOOK_IDLE_COUNT", 0x4c2670: "M2_HOOK_STOP_AFTER"}.get(tgt, "M2_HOOK_UNKNOWN")
    return (kind, addr)


games = []
table = []
port_defaults = {}
va = 0x10ed5e0
while u32(va):
    games.append((cstr(u32(va)), u32(va + 4)))
    va += 8

lines = ["/* Generated by tools/gen_gamedb.py from EMULATOR.EXE (Model 2 Emulator 1.1a).",
         "   ROM entry: type, file, arg, offset, size, crc, flags (see m2rom.c).",
         "   Input: kind, port, bit mask, DirectInput key, name (see m2rom.h). */", ""]
for name, r in games:
    title, zipname, parent, board = cstr(u32(r + 4)), cstr(u32(r + 8)), cstr(u32(r + 0xc)), cstr(u32(r + 0x10))
    w, h = u32(r + 0x20), u32(r + 0x24)
    fps = struct.unpack("<f", rd(r + 0x28))[0]
    head, cnt = u32(r + 0x30), u32(r + 0x34)
    hook = decode_hook(u32(r + 0x3c))
    ents = []
    node = u32(head)
    while node != head:
        f = [u32(node + 8 + 4 * j) for j in range(6)]
        t = f[0]
        if t == 1:
            nm = '"%s"' % cstr(f[1])
        else:
            nm = "NULL"
        # type 1 (file): name, offset, size, crc, flags
        # other types keep the raw second field in "arg": region id (0, 4),
        # source offset (3), fill offset (2) or function address (5)
        arg = 0 if t == 1 else f[1]
        ents.append(f"    {{ {t}, {nm}, 0x{arg:08x}, 0x{f[2]:08x}, 0x{f[3]:08x}, 0x{f[4]:08x}, 0x{f[5]:08x} }},")
        node = u32(node)
    lines.append(f"static const m2_rom_entry roms_{name}[] = {{")
    lines += ents
    lines.append("    { -1, NULL, 0, 0, 0, 0, 0 }")
    if any(e.startswith("    { 5,") for e in ents):
        print("warning: type-5 (function call) entry in", name)
    lines.append("};")
    q = lambda x: f'"{x}"' if x else "NULL"
    table.append(f'    {{ "{name}", {q(title)}, {q(zipname)}, {q(parent)}, {q(board)}, {w}, {h}, {fps:.1f}f, {hook[0]}, 0x{hook[1]:x}, roms_{name}, inputs_{name}, {{ PORTDEF_{name} }}, 0x{u32(r + 0x40):x} }},')
    # inputs: std::list at record+0x14 -> {?, head, count, ?, port defaults (8 bytes), ...}
    inp = u32(r + 0x14)
    ins = []
    if inp:
        head = u32(inp + 4)
        node = u32(head)
        while node and node != head:
            bitport, key, kind, nm = (u32(node + 8 + 4 * j) for j in range(4))
            ins.append(f'    {{ {kind & 0xff}, {bitport & 0xff}, 0x{(bitport >> 8) & 0xff:02x}, 0x{key:08x}, "{cstr(nm) or ""}" }},')
            node = u32(node)
        dflt = rd(inp + 0x10, 8)
    else:
        dflt = bytes(8)
    lines.append(f"static const m2_input inputs_{name}[] = {{")
    lines += ins
    lines.append('    { -1, 0, 0, 0, NULL }')
    lines.append("};")
    port_defaults[name] = ", ".join(f"0x{x:02x}" for x in dflt)
    lines.append("")
lines.append("static const m2_game games[] = {")
lines += [t.replace("PORTDEF_" + n + " ", port_defaults[n] + " ") for t, n in zip(table, [g[0] for g in games])]
lines.append("};")
open(out, "w").write("\n".join(lines) + "\n")
print(len(games), "games written")
for name, r in games:
    print(" ", name, cstr(u32(r + 0x10)), decode_hook(u32(r + 0x3c)))
